
package vn._3lo.voucherservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VoucherService", targetNamespace = "http://3lo.vn/voucherservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VoucherService {


    /**
     * 
     * @param partnerCode
     * @param transRef
     * @param password
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransactionDetail", targetNamespace = "http://3lo.vn/voucherservice", className = "vn._3lo.voucherservice.GetTransactionDetail")
    @ResponseWrapper(localName = "getTransactionDetailResponse", targetNamespace = "http://3lo.vn/voucherservice", className = "vn._3lo.voucherservice.GetTransactionDetailResponse")
    public String getTransactionDetail(
        @WebParam(name = "transRef", targetNamespace = "")
        String transRef,
        @WebParam(name = "partnerCode", targetNamespace = "")
        String partnerCode,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "signature", targetNamespace = "")
        String signature);

    /**
     * 
     * @param issuer
     * @param partnerCode
     * @param cardSerial
     * @param transRef
     * @param password
     * @param cardCode
     * @param signature
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "useCard", targetNamespace = "http://3lo.vn/voucherservice", className = "vn._3lo.voucherservice.UseCard")
    @ResponseWrapper(localName = "useCardResponse", targetNamespace = "http://3lo.vn/voucherservice", className = "vn._3lo.voucherservice.UseCardResponse")
    public String useCard(
        @WebParam(name = "issuer", targetNamespace = "")
        String issuer,
        @WebParam(name = "cardSerial", targetNamespace = "")
        String cardSerial,
        @WebParam(name = "cardCode", targetNamespace = "")
        String cardCode,
        @WebParam(name = "transRef", targetNamespace = "")
        String transRef,
        @WebParam(name = "partnerCode", targetNamespace = "")
        String partnerCode,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "signature", targetNamespace = "")
        String signature);

}
