
package com.elcom.vchgws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VCardServer", targetNamespace = "http://vchgws.elcom.com", wsdlLocation = "file:/home/thangtq/Desktop/VCardServer.xml")
public class VCardServer
    extends Service
{

    private final static URL VCARDSERVER_WSDL_LOCATION;
    private final static WebServiceException VCARDSERVER_EXCEPTION;
    private final static QName VCARDSERVER_QNAME = new QName("http://vchgws.elcom.com", "VCardServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/thangtq/Desktop/VCardServer.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VCARDSERVER_WSDL_LOCATION = url;
        VCARDSERVER_EXCEPTION = e;
    }

    public VCardServer() {
        super(__getWsdlLocation(), VCARDSERVER_QNAME);
    }

    public VCardServer(WebServiceFeature... features) {
        super(__getWsdlLocation(), VCARDSERVER_QNAME, features);
    }

    public VCardServer(URL wsdlLocation) {
        super(wsdlLocation, VCARDSERVER_QNAME);
    }

    public VCardServer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VCARDSERVER_QNAME, features);
    }

    public VCardServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VCardServer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VCardServerPortType
     */
    @WebEndpoint(name = "VCardServerHttpPort")
    public VCardServerPortType getVCardServerHttpPort() {
        return super.getPort(new QName("http://vchgws.elcom.com", "VCardServerHttpPort"), VCardServerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VCardServerPortType
     */
    @WebEndpoint(name = "VCardServerHttpPort")
    public VCardServerPortType getVCardServerHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://vchgws.elcom.com", "VCardServerHttpPort"), VCardServerPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VCARDSERVER_EXCEPTION!= null) {
            throw VCARDSERVER_EXCEPTION;
        }
        return VCARDSERVER_WSDL_LOCATION;
    }

}
